Pandas is to read and manipulte the csv files.

Numpy is for mathematical operations.

In [1]:
import pandas as pd
import numpy as np

Load csv files

In [5]:
group1 = pd.read_csv("../data/raw_sample2/FOOD-DATA-GROUP1.csv")
group2 = pd.read_csv("../data/raw_sample2/FOOD-DATA-GROUP2.csv")
group3 = pd.read_csv("../data/raw_sample2/FOOD-DATA-GROUP3.csv")
group4 = pd.read_csv("../data/raw_sample2/FOOD-DATA-GROUP4.csv")
group5 = pd.read_csv("../data/raw_sample2/FOOD-DATA-GROUP5.csv")

Check Whether They Have the Same Columns

In [6]:
group1.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'food', 'Caloric Value', 'Fat',
       'Saturated Fats', 'Monounsaturated Fats', 'Polyunsaturated Fats',
       'Carbohydrates', 'Sugars', 'Protein', 'Dietary Fiber', 'Cholesterol',
       'Sodium', 'Water', 'Vitamin A', 'Vitamin B1', 'Vitamin B11',
       'Vitamin B12', 'Vitamin B2', 'Vitamin B3', 'Vitamin B5', 'Vitamin B6',
       'Vitamin C', 'Vitamin D', 'Vitamin E', 'Vitamin K', 'Calcium', 'Copper',
       'Iron', 'Magnesium', 'Manganese', 'Phosphorus', 'Potassium', 'Selenium',
       'Zinc', 'Nutrition Density'],
      dtype='str')

In [7]:
group2.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'food', 'Caloric Value', 'Fat',
       'Saturated Fats', 'Monounsaturated Fats', 'Polyunsaturated Fats',
       'Carbohydrates', 'Sugars', 'Protein', 'Dietary Fiber', 'Cholesterol',
       'Sodium', 'Water', 'Vitamin A', 'Vitamin B1', 'Vitamin B11',
       'Vitamin B12', 'Vitamin B2', 'Vitamin B3', 'Vitamin B5', 'Vitamin B6',
       'Vitamin C', 'Vitamin D', 'Vitamin E', 'Vitamin K', 'Calcium', 'Copper',
       'Iron', 'Magnesium', 'Manganese', 'Phosphorus', 'Potassium', 'Selenium',
       'Zinc', 'Nutrition Density'],
      dtype='str')

In [8]:
group3.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'food', 'Caloric Value', 'Fat',
       'Saturated Fats', 'Monounsaturated Fats', 'Polyunsaturated Fats',
       'Carbohydrates', 'Sugars', 'Protein', 'Dietary Fiber', 'Cholesterol',
       'Sodium', 'Water', 'Vitamin A', 'Vitamin B1', 'Vitamin B11',
       'Vitamin B12', 'Vitamin B2', 'Vitamin B3', 'Vitamin B5', 'Vitamin B6',
       'Vitamin C', 'Vitamin D', 'Vitamin E', 'Vitamin K', 'Calcium', 'Copper',
       'Iron', 'Magnesium', 'Manganese', 'Phosphorus', 'Potassium', 'Selenium',
       'Zinc', 'Nutrition Density'],
      dtype='str')

In [9]:
group4.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'food', 'Caloric Value', 'Fat',
       'Saturated Fats', 'Monounsaturated Fats', 'Polyunsaturated Fats',
       'Carbohydrates', 'Sugars', 'Protein', 'Dietary Fiber', 'Cholesterol',
       'Sodium', 'Water', 'Vitamin A', 'Vitamin B1', 'Vitamin B11',
       'Vitamin B12', 'Vitamin B2', 'Vitamin B3', 'Vitamin B5', 'Vitamin B6',
       'Vitamin C', 'Vitamin D', 'Vitamin E', 'Vitamin K', 'Calcium', 'Copper',
       'Iron', 'Magnesium', 'Manganese', 'Phosphorus', 'Potassium', 'Selenium',
       'Zinc', 'Nutrition Density'],
      dtype='str')

In [10]:
group5.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'food', 'Caloric Value', 'Fat',
       'Saturated Fats', 'Monounsaturated Fats', 'Polyunsaturated Fats',
       'Carbohydrates', 'Sugars', 'Protein', 'Dietary Fiber', 'Cholesterol',
       'Sodium', 'Water', 'Vitamin A', 'Vitamin B1', 'Vitamin B11',
       'Vitamin B12', 'Vitamin B2', 'Vitamin B3', 'Vitamin B5', 'Vitamin B6',
       'Vitamin C', 'Vitamin D', 'Vitamin E', 'Vitamin K', 'Calcium', 'Copper',
       'Iron', 'Magnesium', 'Manganese', 'Phosphorus', 'Potassium', 'Selenium',
       'Zinc', 'Nutrition Density'],
      dtype='str')

All five groups have same columns. So, we can simply combine them.

In [11]:
food_df = pd.concat(
    [group1, group2, group3, group4, group5],
    ignore_index=True
)

In [12]:
food_df.shape

(2395, 37)

In [13]:
food_df.head()

,Unnamed: 0.1,Unnamed: 0,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
0,0,0,cream cheese,51,5.0,2.9,1.3,0.200,0.8,0.500,...,0.008,14.100,0.082,0.027,1.300,0.091,15.5,19.100,0.039,7.070
1,1,1,neufchatel cheese,215,19.4,10.9,4.9,0.800,3.1,2.700,...,99.500,0.034,0.100,8.500,0.088,117.300,129.2,0.054,0.700,130.100
2,2,2,requeijao cremoso light catupiry,49,3.6,2.3,0.9,0.000,0.9,3.400,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,5.400
3,3,3,ricotta cheese,30,2.0,1.3,0.5,0.002,1.5,0.091,...,0.097,41.200,0.097,0.096,4.000,0.024,30.8,43.800,0.035,5.196
4,4,4,cream cheese low fat,30,2.3,1.4,0.6,0.042,1.2,0.900,...,22.200,0.072,0.008,1.200,0.098,22.800,37.1,0.034,0.053,27.007

In [14]:
food_df.tail()

,Unnamed: 0.1,Unnamed: 0,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
2390,717,717,jews ear,25,0.095,0.000,0.000,0.000,6.7,0.000,...,15.8,0.4,0.600,24.800,0.040,13.900,42.6,0.034,0.700,24.249
2391,718,718,enoki mushrooms,1,0.099,0.027,0.000,0.010,0.2,0.034,...,0.0,0.0,0.099,0.034,0.500,0.015,3.2,10.800,0.096,0.433
2392,719,719,morel mushrooms,4,0.070,0.056,0.031,0.007,0.7,0.096,...,0.0,5.5,0.056,1.600,2.500,0.060,25.0,53.000,0.069,1.727
2393,720,720,portabella mushrooms raw,19,0.300,0.036,0.016,0.100,3.3,2.200,...,2.6,0.2,0.300,0.000,0.092,92.900,313.0,0.015,0.500,9.400
2394,721,721,oyster mushroom,5,0.035,0.016,0.039,0.099,0.9,0.200,...,0.0,0.5,0.008,0.200,2.700,0.055,18.0,63.000,0.048,1.804

Check for duplicates

In [15]:
food_df.duplicated().sum()

np.int64(0)

In [16]:
food_df["food"].duplicated().sum()

np.int64(0)

In [17]:
food_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2395 entries, 0 to 2394
Data columns (total 37 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0.1          2395 non-null   int64
 1   Unnamed: 0            2395 non-null   int64
 2   food                  2395 non-null   str
 3   Caloric Value         2395 non-null   int64
 4   Fat                   2395 non-null   float64
 5   Saturated Fats        2395 non-null   float64
 6   Monounsaturated Fats  2395 non-null   float64
 7   Polyunsaturated Fats  2395 non-null   float64
 8   Carbohydrates         2395 non-null   float64
 9   Sugars                2395 non-null   float64
 10  Protein               2395 non-null   float64
 11  Dietary Fiber         2395 non-null   float64
 12  Cholesterol           2395 non-null   float64
 13  Sodium                2395 non-null   float64
 14  Water                 2395 non-null   float64
 15  Vitamin A             2395 non-null   float64
 16  Vitamin B1            2395 non-null   float64
 17  Vitamin B11           2395 non-null   float64
 18  Vitamin B12           2395 non-null   float64
 19  Vitamin B2            2395 non-null   float64
 20  Vitamin B3            2395 non-null   float64
 21  Vitamin B5            2395 non-null   float64
 22  Vitamin B6            2395 non-null   float64
 23  Vitamin C             2395 non-null   float64
 24  Vitamin D             2395 non-null   float64
 25  Vitamin E             2395 non-null   float64
 26  Vitamin K             2395 non-null   float64
 27  Calcium               2395 non-null   float64
 28  Copper                2395 non-null   float64
 29  Iron                  2395 non-null   float64
 30  Magnesium             2395 non-null   float64
 31  Manganese             2395 non-null   float64
 32  Phosphorus            2395 non-null   float64
 33  Potassium             2395 non-null   float64
 34  Selenium              2395 non-null   float64
 35  Zinc                  2395 non-null   float64
 36  Nutrition Density     2395 non-null   float64
dtypes: float64(33), int64(3), str(1)
memory usage: 692.4 KB

In [18]:
food_df.isnull().sum()

Unnamed: 0.1            0
Unnamed: 0              0
food                    0
Caloric Value           0
Fat                     0
Saturated Fats          0
Monounsaturated Fats    0
Polyunsaturated Fats    0
Carbohydrates           0
Sugars                  0
Protein                 0
Dietary Fiber           0
Cholesterol             0
Sodium                  0
Water                   0
Vitamin A               0
Vitamin B1              0
Vitamin B11             0
Vitamin B12             0
Vitamin B2              0
Vitamin B3              0
Vitamin B5              0
Vitamin B6              0
Vitamin C               0
Vitamin D               0
Vitamin E               0
Vitamin K               0
Calcium                 0
Copper                  0
Iron                    0
Magnesium               0
Manganese               0
Phosphorus              0
Potassium               0
Selenium                0
Zinc                    0
Nutrition Density       0
dtype: int64

In [19]:
food_df.describe()

,Unnamed: 0.1,Unnamed: 0,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,Protein,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
count,2395.000000,2395.000000,2395.000000,2395.000000,2395.000000,2395.000000,2395.000000,2395.000000,2395.000000,2395.000000,...,2395.000000,2395.000000,2395.000000,2395.000000,2395.000000,2395.000000,2395.000000,2395.000000,2395.000000,2395.000000
mean,272.258038,272.258038,223.769520,10.176276,3.924917,4.133622,2.152844,18.589021,4.457459,13.400777,...,52.047728,9.581689,1.853271,34.429792,5.349964,156.236052,303.833939,52.258006,1.579192,106.929006
std,182.889214,182.889214,384.728244,29.008915,19.502262,12.939587,7.145738,29.406134,13.339929,32.294246,...,115.933379,69.912400,5.155650,71.927990,21.005332,333.257099,589.507589,199.257203,4.937509,173.023891
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,119.000000,119.000000,44.500000,0.300000,0.064000,0.058000,0.071000,0.500000,0.000000,0.800000,...,0.600000,0.040000,0.100000,1.500000,0.037000,0.800000,27.750000,0.016000,0.055000,16.876500
50%,241.000000,241.000000,117.000000,2.100000,0.500000,0.500000,0.400000,6.800000,0.086000,3.500000,...,13.900000,0.100000,0.600000,10.400000,0.200000,42.300000,112.300000,0.053000,0.300000,53.840000
75%,414.500000,414.500000,258.000000,9.400000,2.700000,3.400000,1.700000,25.050000,3.200000,13.300000,...,48.250000,0.400000,1.800000,36.950000,0.700000,171.350000,340.500000,0.090000,1.200000,135.074500
max,721.000000,721.000000,6077.000000,550.700000,672.000000,291.100000,188.000000,390.200000,291.500000,560.300000,...,1283.500000,1890.000000,121.200000,921.600000,451.000000,5490.000000,11336.900000,3308.000000,147.300000,3911.400000

Drop Unnecessary Columns

These are simply index columns that got saved into the CSV.

In [20]:
food_df = food_df.drop(
    columns=[
        "Unnamed: 0",
        "Unnamed: 0.1"
    ]
)

In [21]:
food_df.head()

,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,Protein,Dietary Fiber,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
0,cream cheese,51,5.0,2.9,1.3,0.200,0.8,0.500,0.9,0.0,...,0.008,14.100,0.082,0.027,1.300,0.091,15.5,19.100,0.039,7.070
1,neufchatel cheese,215,19.4,10.9,4.9,0.800,3.1,2.700,7.8,0.0,...,99.500,0.034,0.100,8.500,0.088,117.300,129.2,0.054,0.700,130.100
2,requeijao cremoso light catupiry,49,3.6,2.3,0.9,0.000,0.9,3.400,0.8,0.1,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,5.400
3,ricotta cheese,30,2.0,1.3,0.5,0.002,1.5,0.091,1.5,0.0,...,0.097,41.200,0.097,0.096,4.000,0.024,30.8,43.800,0.035,5.196
4,cream cheese low fat,30,2.3,1.4,0.6,0.042,1.2,0.900,1.2,0.0,...,22.200,0.072,0.008,1.200,0.098,22.800,37.1,0.034,0.053,27.007

Check for duplicates in food

In [22]:
food_df["food"].duplicated().sum()

np.int64(0)

In [23]:
food_df[food_df["food"].duplicated()]

Empty DataFrame
Columns: [food, Caloric Value, Fat, Saturated Fats, Monounsaturated Fats, Polyunsaturated Fats, Carbohydrates, Sugars, Protein, Dietary Fiber, Cholesterol, Sodium, Water, Vitamin A, Vitamin B1, Vitamin B11, Vitamin B12, Vitamin B2, Vitamin B3, Vitamin B5, Vitamin B6, Vitamin C, Vitamin D, Vitamin E, Vitamin K, Calcium, Copper, Iron, Magnesium, Manganese, Phosphorus, Potassium, Selenium, Zinc, Nutrition Density]
Index: []

[0 rows x 35 columns]

In [24]:
food_df["food"].sample(20)

1634                sisymbrium seeds
2394                 oyster mushroom
1982                  spray dressing
1799                    banana bread
1646          pistachio nuts roasted
2175                tree fern cooked
2176                 yellow corn raw
738                  chocolate syrup
511                  scallops cooked
1530                     prune juice
2120                     leeks dried
1074             garden cress cooked
1411                chicken back raw
434                        shark raw
1858    oatmeal cookies with raisins
1246        canadian style bacon raw
1759                blueberry muffin
2057               meatless meatloaf
1990          green goddess dressing
542                   octopus cooked
Name: food, dtype: str

In [25]:
food_df.columns = (
    food_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [26]:
food_df.columns

Index(['food', 'caloric_value', 'fat', 'saturated_fats',
       'monounsaturated_fats', 'polyunsaturated_fats', 'carbohydrates',
       'sugars', 'protein', 'dietary_fiber', 'cholesterol', 'sodium', 'water',
       'vitamin_a', 'vitamin_b1', 'vitamin_b11', 'vitamin_b12', 'vitamin_b2',
       'vitamin_b3', 'vitamin_b5', 'vitamin_b6', 'vitamin_c', 'vitamin_d',
       'vitamin_e', 'vitamin_k', 'calcium', 'copper', 'iron', 'magnesium',
       'manganese', 'phosphorus', 'potassium', 'selenium', 'zinc',
       'nutrition_density'],
      dtype='str')

let's give a final check for duplicates

In [27]:
food_df["food"].duplicated().sum()

np.int64(0)

Checklist

1. Unnecessary columns removed

✔️ Yes

Unnamed: 0

Unnamed: 0.1

are gone.

2. Column names standardized

✔️ Yes

caloric_value

dietary_fiber

vitamin_b12

nutrition_density

This follows Python naming conventions.

3. Missing values

✔️ None

0 missing values

4. Numeric columns

✔️ Already numeric.

No conversion needed.

5. Food names

From the sample:

banana bread

No duplicates in food names. This is suitable dataset.

With this step, we can conclude data preprocessing and store it in processed folder.

In [28]:
food_df.to_csv(
    "../data/processed/food_nutrition.csv",
    index=False
)